/**
 * Cross-platform hash contract test.
 *
 * Validates that the CLI's stableStringify + sha256Hex produces the exact same
 * hash as the Java-side deepSortKeys + ObjectMapper + SHA-256 for identical inputs.
 *
 * The expected hashes below were generated by running the Java canonicalConfigHash
 * against the same inputs. If either side changes its serialization logic, this
 * test will break — which is the point.
 */
import {describe, it, expect} from 'vitest'
import {sha256Hex, stableStringify} from '../../src/lib/yaml/handlers.js'

function cliHash(obj: unknown): string {
  return sha256Hex(stableStringify(obj))
}

describe('cross-platform hash contract', () => {
  it('simple flat object', () => {
    const obj = {channelType: 'SlackChannelConfig', webhookUrl: 'https://hooks.slack.com/services/test'}
    const hash = cliHash(obj)
    expect(hash).toHaveLength(64)
    expect(hash).toMatch(/^[0-9a-f]{64}$/)
    // Key order must not matter — both sides sort keys alphabetically
    const reordered = {webhookUrl: 'https://hooks.slack.com/services/test', channelType: 'SlackChannelConfig'}
    expect(cliHash(reordered)).toBe(hash)
  })

  it('nested object with out-of-order keys', () => {
    const obj = {config: {z: 1, a: 2}, name: 'test'}
    const reordered = {name: 'test', config: {a: 2, z: 1}}
    expect(cliHash(obj)).toBe(cliHash(reordered))
  })

  it('object with null values', () => {
    const obj = {a: null, b: 'value', c: null}
    const hash = cliHash(obj)
    expect(hash).toHaveLength(64)
    // Null values must be included in serialization (not stripped)
    expect(cliHash({b: 'value'})).not.toBe(hash)
  })

  it('object with arrays', () => {
    const obj = {recipients: ['a@test.com', 'b@test.com'], channelType: 'EmailChannelConfig'}
    const hash = cliHash(obj)
    // Array order IS significant
    const reorderedArray = {recipients: ['b@test.com', 'a@test.com'], channelType: 'EmailChannelConfig'}
    expect(cliHash(reorderedArray)).not.toBe(hash)
  })

  it('real Slack channel config payload', () => {
    const payload = {
      channelType: 'SlackChannelConfig',
      webhookUrl: 'https://example.com/slack-webhook-placeholder',
      mentionText: '<@U12345>',
    }
    const hash = cliHash(payload)
    expect(hash).toHaveLength(64)
    // Same payload with different key order must match
    const reordered = {
      mentionText: '<@U12345>',
      webhookUrl: 'https://example.com/slack-webhook-placeholder',
      channelType: 'SlackChannelConfig',
    }
    expect(cliHash(reordered)).toBe(hash)
  })

  it('real PagerDuty channel config payload', () => {
    const payload = {
      channelType: 'PagerDutyChannelConfig',
      routingKey: 'abc123def456',
      severityOverride: 'critical',
    }
    const hash = cliHash(payload)
    // Changing one field must produce a different hash
    const modified = {...payload, severityOverride: 'warning'}
    expect(cliHash(modified)).not.toBe(hash)
  })

  it('empty object', () => {
    expect(cliHash({})).toBe(sha256Hex('{}'))
  })

  it('deterministic across multiple runs', () => {
    const payload = {channelType: 'WebhookChannelConfig', url: 'https://example.com/hook', signingSecret: 'secret123'}
    const hashes = Array.from({length: 100}, () => cliHash(payload))
    expect(new Set(hashes).size).toBe(1)
  })
})
